-- =====================================================================
-- Creava Sales Engine — schema Postgres (Supabase)
-- Execute no Supabase: SQL Editor -> New query -> colar -> Run.
-- É seguro rodar mais de uma vez (idempotente).
-- =====================================================================

-- Listas de prospecção: cada busca no Google Maps vira uma "pasta".
create table if not exists lists (
  id bigint generated by default as identity primary key,
  name text not null,
  segment text,
  city text,
  neighborhood text,
  query_text text,
  pages integer not null default 1,
  status text not null default 'OPEN',
  found integer not null default 0,
  imported integer not null default 0,
  duplicates integer not null default 0,
  already_seen integer not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists companies (
  id bigint generated by default as identity primary key,
  name text not null,
  segment text,
  city text,
  state text,
  website text,
  phone text,
  instagram text,
  google_place_id text,
  cnpj text,
  legal_name text,
  cnae text,
  company_size text,
  registration_status text,
  opened_at text,
  capital double precision,
  address text,
  category text,
  rating double precision,
  reviews_count integer,
  domain text,
  phone_normalized text,
  dedupe_key text,
  lead_status text not null default 'DISCOVERED',
  disqualified_reason text,
  list_id bigint references lists(id) on delete set null,
  maps_url text,
  business_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- bancos criados antes das listas
alter table companies add column if not exists list_id bigint references lists(id) on delete set null;
alter table companies add column if not exists maps_url text;
alter table companies add column if not exists business_status text;
create index if not exists idx_companies_list on companies (list_id);

create unique index if not exists uq_companies_google_place_id
  on companies (google_place_id) where google_place_id is not null;
create unique index if not exists uq_companies_cnpj
  on companies (cnpj) where cnpj is not null;
create index if not exists idx_companies_name on companies (name);
create index if not exists idx_companies_domain on companies (domain);
create index if not exists idx_companies_phone on companies (phone_normalized);
create index if not exists idx_companies_dedupe_key on companies (dedupe_key);
create index if not exists idx_companies_lead_status on companies (lead_status);

create table if not exists company_sources (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  source_type text not null,
  source_id text,
  raw_data text,
  created_at timestamptz not null default now()
);
create index if not exists idx_company_sources_company on company_sources (company_id);

create table if not exists website_snapshots (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  url text not null,
  facts text not null,
  fetched_at timestamptz not null default now()
);
create index if not exists idx_snapshots_company on website_snapshots (company_id);

create table if not exists signals (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  type text not null,
  value text,
  evidence text not null,
  source text not null,
  confidence double precision not null default 1,
  created_at timestamptz not null default now()
);
create index if not exists idx_signals_company on signals (company_id);

create table if not exists company_scores (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  fit integer not null,
  need integer not null,
  capacity integer not null,
  intent integer not null,
  total integer not null,
  confidence double precision not null,
  reasons text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_scores_company on company_scores (company_id);

create table if not exists ai_analyses (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  summary text not null,
  main_problem text not null,
  opportunity text not null,
  recommended_offer text not null,
  outreach_angle text not null,
  confidence double precision not null,
  model text,
  recommended_services text,
  bottlenecks text,
  created_at timestamptz not null default now()
);
alter table ai_analyses add column if not exists recommended_services text;
alter table ai_analyses add column if not exists bottlenecks text;
create index if not exists idx_ai_company on ai_analyses (company_id);

create table if not exists prospects (
  id bigint generated by default as identity primary key,
  company_id bigint not null unique references companies(id) on delete cascade,
  status text not null default 'READY',
  priority text not null default 'NORMAL',
  score integer not null default 0,
  next_action text,
  next_action_at timestamptz,
  qualification_notes text,
  lost_reason text,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_prospects_status on prospects (status);

create table if not exists tasks (
  id bigint generated by default as identity primary key,
  prospect_id bigint not null references prospects(id) on delete cascade,
  type text not null,
  title text not null,
  description text,
  priority text not null default 'NORMAL',
  due_at timestamptz,
  completed_at timestamptz,
  outcome text,
  created_at timestamptz not null default now()
);
create index if not exists idx_tasks_due_at on tasks (due_at);
create index if not exists idx_tasks_prospect_id on tasks (prospect_id);
create index if not exists idx_tasks_open on tasks (completed_at) where completed_at is null;

create table if not exists activities (
  id bigint generated by default as identity primary key,
  prospect_id bigint not null references prospects(id) on delete cascade,
  type text not null,
  channel text,
  content text,
  metadata text,
  occurred_at timestamptz not null default now()
);
create index if not exists idx_activities_prospect_id on activities (prospect_id);
create index if not exists idx_activities_type on activities (type);

create table if not exists deals (
  id bigint generated by default as identity primary key,
  prospect_id bigint not null references prospects(id) on delete cascade,
  service_type text,
  title text not null,
  value double precision not null default 0,
  probability integer not null default 50,
  status text not null default 'OPEN',
  expected_close_at timestamptz,
  closed_at timestamptz,
  recurring integer not null default 0,
  lost_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_deals_prospect_id on deals (prospect_id);
create index if not exists idx_deals_status on deals (status);

create table if not exists meetings (
  id bigint generated by default as identity primary key,
  prospect_id bigint not null references prospects(id) on delete cascade,
  scheduled_at timestamptz not null,
  notes text,
  need text,
  budget text,
  decision_maker text,
  timeline text,
  created_at timestamptz not null default now()
);

create table if not exists proposals (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references deals(id) on delete cascade,
  prospect_id bigint not null references prospects(id) on delete cascade,
  value double precision not null,
  description text,
  sent_at timestamptz not null default now(),
  valid_until timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists jobs (
  id bigint generated by default as identity primary key,
  type text not null,
  status text not null default 'PENDING',
  progress integer not null default 0,
  error text,
  result text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create table if not exists api_usage (
  id bigint generated by default as identity primary key,
  provider text not null,
  operation text not null,
  requests integer not null default 1,
  tokens integer not null default 0,
  estimated_cost double precision not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists playbook_scripts (
  id bigint generated by default as identity primary key,
  segment text not null,
  kind text not null,
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);


-- ---------------------------------------------------------------------
-- v2: serviços, canais de contato, abordagens e registro anti-repetição
-- ---------------------------------------------------------------------
create table if not exists services (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text not null,
  pain_points text,
  active integer not null default 1,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists company_channels (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  kind text not null,
  value text not null,
  url text,
  label text,
  source text not null,
  created_at timestamptz not null default now(),
  unique (company_id, kind, value)
);
create index if not exists idx_channels_company on company_channels (company_id);
create index if not exists idx_channels_kind on company_channels (kind);

create table if not exists company_approaches (
  id bigint generated by default as identity primary key,
  company_id bigint not null references companies(id) on delete cascade,
  channel text not null,
  service_key text,
  angle text not null,
  message text not null,
  evidence_used text,
  source text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_approaches_company on company_approaches (company_id);

-- Todo lugar do Google já coletado fica aqui, mesmo que a empresa seja
-- apagada/mesclada depois: nunca é importado (nem cobrado) de novo.
create table if not exists seen_places (
  google_place_id text primary key,
  company_id bigint references companies(id) on delete set null,
  times_seen integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists discovery_searches (
  id bigint generated by default as identity primary key,
  query_key text not null unique,
  segment text not null,
  city text not null,
  neighborhood text,
  pages integer not null default 1,
  runs integer not null default 1,
  last_found integer not null default 0,
  last_imported integer not null default 0,
  last_run_at timestamptz not null default now()
);

-- Conversas por empresa (histórico organizado) e lista de supressão.
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  company_id bigint not null unique references companies(id) on delete cascade,
  opted_out integer not null default 0,
  handoff_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists conversation_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references conversations(id) on delete cascade,
  company_id bigint not null references companies(id) on delete cascade,
  direction text not null,
  author text not null,
  body text not null,
  status text not null,
  intent text,
  model text,
  edited integer not null default 0,
  evidence_used text,
  created_at timestamptz not null default now()
);
create index if not exists idx_conv_messages_conv on conversation_messages (conversation_id);
create index if not exists idx_conv_messages_company on conversation_messages (company_id);

-- Quem pediu para não ser contatado: consultada antes de qualquer abordagem.
create table if not exists suppressions (
  id bigint generated by default as identity primary key,
  kind text not null,
  value text not null,
  reason text,
  created_at timestamptz not null default now(),
  unique (kind, value)
);

-- ---------------------------------------------------------------------
-- Segurança: somente usuários autenticados acessam qualquer tabela.
-- (Desative "Allow new users to sign up" em Authentication > Providers.)
-- ---------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'lists','companies','company_sources','website_snapshots','signals',
    'company_scores','ai_analyses','prospects','tasks','activities',
    'deals','meetings','proposals','jobs','api_usage','settings',
    'playbook_scripts','services','company_channels','company_approaches',
    'seen_places','discovery_searches','conversations','conversation_messages',
    'suppressions'
  ]
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "authenticated full access" on %I', t);
    execute format(
      'create policy "authenticated full access" on %I for all to authenticated using (true) with check (true)',
      t
    );
    execute format('revoke all on %I from anon', t);
    execute format('grant select, insert, update, delete on %I to authenticated', t);
  end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;

-- Usado após importar backup / resetar: realinha os contadores de id.
create or replace function reset_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare r record;
begin
  for r in
    select c.table_name, c.column_name,
           pg_get_serial_sequence(format('%I.%I', c.table_schema, c.table_name), c.column_name) as seq
    from information_schema.columns c
    where c.table_schema = 'public' and c.is_identity = 'YES'
  loop
    if r.seq is not null then
      execute format(
        'select setval(%L, coalesce((select max(%I) from %I), 0) + 1, false)',
        r.seq, r.column_name, r.table_name
      );
    end if;
  end loop;
end $$;

grant execute on function reset_identity_sequences() to authenticated;
